version: "3"
services:
  app:
    build: .
    container_name: dental24x7-backend
    environment:
      - DATABASE_URL=mongodb+srv://danAdmin:GdPexhKCUf3dvnG9@cluster0.xpbgqre.mongodb.net/dooss_db?retryWrites=true&w=majority
      - JWT_SECRET=24x7Direct
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
