version: "3"
services:
  app:
    build: .
    container_name: dental24x7-backend
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env
